[package]
name = "oxono"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = { version = "0.28.1", optional = true }
ratatui = { version = "0.29.0", optional = true }

[features]
default = [ "tui" ]
tui = ["crossterm", "ratatui"]